### ISSUE TITLE
Question: why unobserve/observe the document on changes?

### ISSUE THREAD

**Issue by fcollonval** [jupyter-server/jupyter_server_ydoc#38]
In JupyterLab front end, we are not doing that. Is it an artifact from an earlier version or a behavior difference in y_py compared to yjs?

https://github.com/jupyter-server/jupyter_server_ydoc/blob/d7e728b0c773977c6a307d7a8878b40c6be3a13d/jupyter_server_ydoc/ydoc.py#L250-L253

**Comment by davidbrochart** [comment]
Thinking more about it now, it might not be necessary indeed.
