### ISSUE TITLE
Missing dependency on jupyter_server_fileid

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter_server_ydoc#48]
## Description

This extension requires jupyter_server_fileid to work properly, but it doesn't depend on its python package. Thus, the default experience for users is essentially broken and we don't have documentation to fill in the gap.

## Reproduce

Install JupyterLab 3.6.x and `jupyter_server_ydoc` and use JLab with RTC. You will see a number of instabilities such as the filename changing between a name and a UUID every second or so. 

## Expected behavior

This extension should have a hard dependency on `jupyter_server_fileid` so that users always have a good RTC experience.

**Comment by davidbrochart** [comment]
I thought we were going to extract out the `ArbritraryFileIdManager` into a required dependency of `jupyter-server`, and have the `LocalFileIdManager` an optional dependency?
Otherwise I'm fine with making `jupyter-server-ydoc` depend on `jupyter-server-fileid`.

**Comment by ellisonbg** [comment]
Sorry, you may have missed the follow up conversation in the Jupyter Server meeting. We decided the following:

* Keep both file id managers in the same repo and package.
* Always set the `ArbitraryFileIdManager` to the default, but allow users to configure another one.
* Have `jupyter_server_ydoc` take a hard dependency on jupyter server file id.

**Comment by davidbrochart** [comment]
Thanks Brian, I opened #51.
