### ISSUE TITLE
Allow sqlite db to be saved in a different location

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter_server_ydoc#49]
### Problem

We are testing this on an NFS filesystem and finding that the sqlite ystore that is default is struggling to keep up on this filesystem. To resolve this, we are experimenting with putting the sqlite db on a different (and faster) filesystem. We have made changes in our local source to change the location and it seems to resolve the performance issues, but we would like the db location to be configurable.

### Proposed Solution

Add a new configurable trait to set the location of the sqlite db.

**Comment by ellisonbg** [comment]
I should note, when we moved the sqlite db, we began to see this exception raised in the logs:

https://github.com/jupyter-server/jupyter_server_ydoc/blob/v0.1.14/jupyter_server_ydoc/ydoc.py#L124

**Comment by davidbrochart** [comment]
This is strange, the exception you're mentioning is related to the file ID SQLite database, not the YStore SQLite database.

**Comment by davidbrochart** [comment]
> Add a new configurable trait to set the location of the sqlite db.

There is already a [collaborative_ystore_class](https://github.com/jupyterlab/jupyterlab/blob/288b7f79abb3eaca9b7db4d416a5fbdee7cf13cb/jupyterlab/labapp.py#L583-L589) trait in JupyterLab, that allows to even use another backend for storing Y updates (can be a [file](https://github.com/y-crdt/ypy-websocket/blob/9fb2fad3a20d8df833f8ea462d2522847d435ecf/ypy_websocket/ystore.py#L44), a [temporary file](https://github.com/y-crdt/ypy-websocket/blob/9fb2fad3a20d8df833f8ea462d2522847d435ecf/ypy_websocket/ystore.py#L82), or an [SQLite database](https://github.com/y-crdt/ypy-websocket/blob/9fb2fad3a20d8df833f8ea462d2522847d435ecf/ypy_websocket/ystore.py#L107) for now).
To change the location of the SQLite database, you need to subclass [SQLiteYStore](https://github.com/y-crdt/ypy-websocket/blob/9fb2fad3a20d8df833f8ea462d2522847d435ecf/ypy_websocket/ystore.py#L107) and override `db_path`:
```py
from ypy_websocket.ystore import SQLiteYStore

class MySQLiteYStore(SQLiteYStore):
    db_path = "path/to/my/ystore.db"
```
Then pass this class e.g. at the command line:
```console
jupyter lab --collaborative --LabApp.collaborative_ystore_class=my_module.MySQLiteYStore
```

**Comment by davidbrochart** [comment]
The way to pass the YStore class at the CLI is now:
```console
jupyter lab --collaborative --YDocExtension.ystore_class=my_module.MySQLiteYStore
```
