### ISSUE TITLE
Improve configurability

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter_server_ydoc#53]
## Description

This extension relies on configurable traits in another Jupyter package (namely JupyterLab). We have worked very hard in Jupyter to build a configuration system that co-locates all dimensions of configuration in one place: 1) declaration of a configurable trait, 2) validate of its values, 3) default values for that trait, 4) its usage.

This repo is introducing a pattern that splits these things across multiple packages, which means they can fall out of sync and break things.

As an example, today in the JupyterLab all, attendees tried to use JupyterLab RTC, but found that the file was never being saved to disk. I believe that this problem is coming from this code here:

https://github.com/jupyter-server/jupyter_server_ydoc/blob/main/jupyter_server_ydoc/ydoc.py#L257

If a version of JupyterLab is used with this that doesn't have the configurable trait, the document is never saved to disk. I believe this was the bug seen in the JLab meeting today, but I think there is a deep issue about separating the different parts of config across packages. 

I believe we should make this extension itself have configurable traits with default in its own code base rather than having those in different packages. Because this will be a breaking change, I think we should make this change before the 3.6 final release.

**Comment by davidbrochart** [comment]
I opened #54.
